import Header from "./Header/Header"
import Footer from "./Footer/Footer"
import Login from "./Login"
import About from "./About"
import Signup from "./Signup"
import Home from "./Home"
import LineChart from "./LineChart/LineChart"
import VehicleCard from "./VehicleCard.jsx/VehicleCard"
import UserDashboard from "./UserDashBoard/UserDashBoard"
import Map from "./Map/Map"
import AddVehicle from "./AddVehicle"
// import SearchStartEnd from "./Map/SearchStartEnd"
import VehicleJourney from "./VehicleJourney"
import SearchPlace from "./Map/SearchPlace"

export {Header, Footer, Login, About, Signup, Home, LineChart, VehicleCard, UserDashboard, Map, AddVehicle, VehicleJourney,  SearchPlace}